### ISSUE TITLE
Enhancing with any type of cube (e.g. def cube for weps) possible

### ISSUE THREAD

**Issue by rapmike1** [NGemity/RZEmulator#12]
you can upgrade a wep with def cubes lol
and armor with strikes lol

strikes and Def cubes work for both gears and weapons

**Comment by Xijezu** [comment]
`    if (pCube == nullptr
        || pCube->m_Instance.Code != pInfo->nNeedItemCode
        || (pMixInfo->type == MIX_TYPE::MIX_ENHANCE_WITHOUT_FAIL && pPowder == nullptr)
        /*|| pInfo->nMaxEnhance <= pMainMaterial->m_Instance.nEnhance*/)
    {
        Messages::SendResult(pPlayer, 256, TS_RESULT_INVALID_ARGUMENT, 0);
        return false;
}`
That shouldn't work at all actually. Can you still reproduce it?

**Comment by Xijezu** [comment]
Nvm, bug is still existant in the current rev.
