### ISSUE TITLE
Skill Cards

### ISSUE THREAD

**Issue by rapmike1** [NGemity/RZEmulator#20]
### Version
[server.worldserver] Rappelz-Emulator rev. e7b5798e38d1 2018-03-02 22:10:41 +0100 (master branch) (Win64, 'Release') (worldserver)

### Expected Behaviour 
Equip 1 skill card of same type at a time like +1 blessing of vit

### Actual Behaviour
you can keep equiping the same card over and over lol 2 +1 Blessing Of vit at same time and so on 
### Steps to reproduce the behaviour
reloged did same thing over and over 
### Additional information
none

**Comment by Xijezu** [comment]
Fixed with 574abcd.
