### ISSUE TITLE
Pet doesn't recall on death

### ISSUE THREAD

**Issue by XavierDeFawks** [NGemity/RZEmulator#21]
### Version
Not sure. Found on public test server.

### Expected Behaviour 
Pet should be recalled when player dies.

### Actual Behaviour
Pet is not recalled when player dies and continues attacking the mob.
### Steps to reproduce the behaviour
Die while attacking a mob.

**Comment by Xijezu** [comment]
Want to fix it yourself @XavierDeFawks ?

**Comment by Xijezu** [comment]
Fixed with 0456373
