### ISSUE TITLE
Hot Bars not saving

### ISSUE THREAD

**Issue by rapmike1** [NGemity/RZEmulator#26]
Testing server

### Expected Behaviour 
Save hot bars when adding things to them 

### Actual Behaviour
Undoes all Things that you do to the hot bar and resets to before you logged into the game 

### Steps to reproduce the behaviour
repeated this bug about 40 times

**Comment by 0x5248** [comment]
@XavierDeFawks fixed it https://github.com/NGemity/RZEmulator/commit/840a746f5e50ecfa79d7ff6dc99ccf009beb5ef0
