### ISSUE TITLE
Droping Items from Inventory

### ISSUE THREAD

**Issue by 0x5248** [NGemity/RZEmulator#32]
### Version
Rappelz-Emulator rev. afad37ff7e37 2018-07-31 23:23:31 +0200 (master branch) (Unix, 'Debug') (worldserver)

### Expected Behaviour 
Item lands on ground and can be picked up.

### Actual Behaviour
Nothing happens.

### Steps to reproduce the behaviour
Take any Item from your inventory - for example your weapon and try to drop it onto the ground.

**Comment by Xijezu** [comment]
Yes, that's known. I've added a temp implementation of that packet already, but it's not enabled in the handler if I'm not mistaken.
The actual implementation is more complex but not that important yet - if anyone is interested, feel free to pick it up @0x5248 @XavierDeFawks @Jynsaillar

**Comment by 0x5248** [comment]
fixed by @max071985 
https://github.com/NGemity/RZEmulator/commit/73cb4dc0aaf6dd25a323412ee4e2d54f20a4d57c
