### ISSUE TITLE
creature mastery 

### ISSUE THREAD

**Issue by petpowwer** [NGemity/RZEmulator#52]
### Version
Listed on startup, e.g.  
Rappelz-Emulator rev. xxxxxx+ 2018-xx0xx xx:xx:xx + xxxx (master branch) (Unix, 'Debug') (worldserver)

### Expected Behaviour 
pet gets stronger as lvled 

### Actual Behaviour
nothing changes 
### Steps to reproduce the behaviour
learn  creature mastery

**Comment by Xijezu** [comment]
The skill itself is implemented and is working just fine. 
The stats of the pets just don't get updated visually. Here as a comparison:
Lv10 Creature Mastery on a Lv1 red pixie:
https://i.xijezu.com/pQHrU.png
unimplemented/Lv1 Creature Mastery on a Lv1 red pixie:
https://i.xijezu.com/FPxgi.png
