### ISSUE TITLE
Party Server DC

### ISSUE THREAD

**Issue by rapmike1** [NGemity/RZEmulator#6]
this is what happens when a player joins a party not as leader and then logs out or leaves the party 

![image](https://user-images.githubusercontent.com/35908949/36573684-3196015c-1810-11e8-956a-7e4861ec11b9.png)

**Comment by Xijezu** [comment]
I think this may be fixed by now, too?

**Comment by Xijezu** [comment]
Bug has been fixed already, as mentioned by Cronx
