### ISSUE TITLE
Creature cards of actively summoned creatures are sellable

### ISSUE THREAD

**Issue by NitoBell** [NGemity/RZEmulator#73]
### Version
Listed on startup, e.g.  
Rappelz-Emulator rev. xxxxxx+ 2018-xx0xx xx:xx:xx + xxxx (master branch) (Unix, 'Debug') (worldserver)

### Expected Behaviour 
You should not be able to sell the creature card of a creature which is currently summoned or used in your creature formation. 
Only not equiped creature cards (empty or tamed) should be sellable and being able to be listed on merchant lists, etc. 

### Actual Behaviour

The card of the actively summoned creature is listed with the items you can sell at a npc which sells and buys stuff from players. You can sell them causing the server to malfunction. 

### Steps to reproduce the behaviour

Tame a pet. 
Summon a said pet. 
Go to a merchant/npc which sells and buys stuff. 
Locate the creature card of your currently actviely summoned creature.
Sell it. 

### Additional information

The creature remains summoned after selling the card. The icon in the creature information still displays the creature icon and information. 
When you enter the creature formation (via alt+Y or via menu) the icon disappears from the creature info. 
The first spot of the creature formation remains marked as being used (blue borders around it). 

When logging out the server does not crash. 
When logging in the server crashes.

**Comment by 0x5248** [comment]
https://github.com/NGemity/RZEmulator/pull/66/commits/bdcd35b74925f00fdea46b6b099ce4c4acf3a457
is the fix for that
