### ISSUE TITLE
broken class

### ISSUE THREAD

**Issue by petpowwer** [NGemity/RZEmulator#78]
### Version
Listed on startup, e.g.  
Rappelz-Emulator rev. xxxxxx+ 2018-xx0xx xx:xx:xx + xxxx (master branch) (Unix, 'Debug') (worldserver)

### Expected Behaviour 

summoner mastery makes pets stronger
### Actual Behaviour
does nothing
### Steps to reproduce the behaviour
make any class and learn the skill

**Comment by Xijezu** [comment]
Duplicate of #52
