### ISSUE TITLE
Pet equipment locked to character

### ISSUE THREAD

**Issue by ThunderNikk** [NGemity/RZEmulator#9]
### Version
Listed on startup, e.g.  
Rappelz-Emulator rev. xxxxxx+ 2018-xx0xx xx:xx:xx + xxxx (master branch) (Unix, 'Debug') (worldserver)

**Comment by Xijezu** [comment]
Probably fixed by now, too, because

> Crash the server by placing pets in warehouse
is already fixed

**Comment by Xijezu** [comment]
Yep, apparentely fixed based on what @ThunderNikk said on Discord.
